FROM cosmtrek/air:v1.52.3 AS air
FROM golang:1.22-alpine

COPY --from=air /go/bin/air /usr/local/bin/air

WORKDIR /src/backend

EXPOSE 8080

ENV QURL_LISTEN_ADDR=:8080

CMD ["air", "-c", ".air.toml"]
